import type { PlantPresetInsertInput } from "@/lib/db/zod";

export const builtInPlantPresets: ReadonlyArray<PlantPresetInsertInput> = [
  {
    commonName: "Monstera",
    scientificName: "Monstera deliciosa",
    careDifficulty: "easy",
    light: "Bright indirect light",
    water: "Water when top 2-3cm of soil is dry",
    humidity: "50% or higher",
    temperature: "18-27\u00B0C (65-80\u00B0F)",
    soil: "Well-draining aroid mix with bark and perlite",
    fertilizer: "Balanced liquid fertilizer monthly during growth",
    petToxicity: "toxic-pets",
    careSummary:
      "Forgiving climber that loves a moss pole. Wipe the big leaves and let the soil dry between waterings.",
  },
  {
    commonName: "Pothos",
    scientificName: "Epipremnum aureum",
    careDifficulty: "easy",
    light: "Low to bright indirect",
    water: "Water when soil is half dry",
    humidity: "Average household humidity",
    temperature: "16-29\u00B0C (60-85\u00B0F)",
    soil: "Standard houseplant mix",
    fertilizer: "Diluted balanced fertilizer every 4-6 weeks",
    petToxicity: "toxic-pets",
    careSummary:
      "Bulletproof trailing vine. Tolerates low light, neglect, and is easy to propagate from cuttings.",
  },
  {
    commonName: "Snake Plant",
    scientificName: "Dracaena trifasciata",
    careDifficulty: "easy",
    light: "Low to bright indirect",
    water: "Let soil dry completely between waterings",
    humidity: "Tolerates dry air",
    temperature: "15-29\u00B0C (60-85\u00B0F)",
    soil: "Cactus or succulent mix",
    fertilizer: "Light feed twice per growing season",
    petToxicity: "toxic-pets",
    careSummary:
      "Architectural and forgiving. Overwatering is the only real risk\u2014keep it on the dry side.",
  },
  {
    commonName: "Peace Lily",
    scientificName: "Spathiphyllum wallisii",
    careDifficulty: "moderate",
    light: "Medium indirect, tolerates low",
    water: "Keep evenly moist, droops when thirsty",
    humidity: "50% or higher preferred",
    temperature: "18-27\u00B0C (65-80\u00B0F)",
    soil: "Rich, well-draining houseplant mix",
    fertilizer: "Balanced fertilizer every 6 weeks",
    petToxicity: "toxic-pets",
    careSummary:
      "Drama queen that bounces back fast. The leaf droop is a clear cue it needs water.",
  },
  {
    commonName: "ZZ Plant",
    scientificName: "Zamioculcas zamiifolia",
    careDifficulty: "easy",
    light: "Low to bright indirect",
    water: "Water sparingly, every 2-3 weeks",
    humidity: "Tolerates dry air",
    temperature: "18-26\u00B0C (65-79\u00B0F)",
    soil: "Well-draining mix with perlite",
    fertilizer: "Light feed every 2 months in growth season",
    petToxicity: "toxic-pets",
    careSummary:
      "Stores water in its rhizomes, so under-water rather than over-water. Slow but indestructible.",
  },
  {
    commonName: "Spider Plant",
    scientificName: "Chlorophytum comosum",
    careDifficulty: "easy",
    light: "Bright indirect",
    water: "Water when top 2cm of soil is dry",
    humidity: "Average",
    temperature: "13-27\u00B0C (55-80\u00B0F)",
    soil: "Standard houseplant mix",
    fertilizer: "Balanced fertilizer monthly in spring/summer",
    petToxicity: "non-toxic",
    careSummary:
      "Pet-safe and prolific. Produces baby plantlets that root quickly in water or soil.",
  },
  {
    commonName: "Fiddle Leaf Fig",
    scientificName: "Ficus lyrata",
    careDifficulty: "hard",
    light: "Bright indirect, some morning sun",
    water: "Water when top 3-5cm of soil is dry",
    humidity: "50% or higher",
    temperature: "18-24\u00B0C (65-75\u00B0F)",
    soil: "Well-draining loam mix",
    fertilizer: "Monthly during growing season",
    petToxicity: "toxic-pets",
    careSummary:
      "Statement tree that hates being moved. Pick a bright spot and stick with a steady routine.",
  },
  {
    commonName: "Rubber Plant",
    scientificName: "Ficus elastica",
    careDifficulty: "moderate",
    light: "Bright indirect",
    water: "Water when top 2cm of soil is dry",
    humidity: "Average to high",
    temperature: "16-24\u00B0C (60-75\u00B0F)",
    soil: "Well-draining mix",
    fertilizer: "Balanced fertilizer monthly in growth",
    petToxicity: "toxic-pets",
    careSummary:
      "Glossy upright tree with deep burgundy varieties. Wipe leaves regularly so they keep their shine.",
  },
  {
    commonName: "Aloe Vera",
    scientificName: "Aloe barbadensis miller",
    careDifficulty: "easy",
    light: "Bright direct or strong indirect",
    water: "Deep water, then let dry completely",
    humidity: "Low; thrives in dry rooms",
    temperature: "13-27\u00B0C (55-80\u00B0F)",
    soil: "Cactus or succulent mix",
    fertilizer: "Light feed in spring only",
    petToxicity: "toxic-pets",
    careSummary:
      "Useful and tough. Treat like a succulent\u2014lots of light, infrequent water.",
  },
  {
    commonName: "Jade Plant",
    scientificName: "Crassula ovata",
    careDifficulty: "easy",
    light: "Bright direct light",
    water: "Soak and dry; very drought tolerant",
    humidity: "Low",
    temperature: "16-24\u00B0C (60-75\u00B0F)",
    soil: "Cactus or succulent mix",
    fertilizer: "Diluted feed every 2-3 months",
    petToxicity: "toxic-pets",
    careSummary:
      "Slow-growing succulent tree. Stems stay sturdy with bright light and infrequent watering.",
  },
  {
    commonName: "Calathea",
    scientificName: "Goeppertia orbifolia",
    careDifficulty: "hard",
    light: "Medium indirect, no direct sun",
    water: "Keep evenly moist with filtered water",
    humidity: "60% or higher",
    temperature: "18-27\u00B0C (65-80\u00B0F)",
    soil: "Peat-based mix that retains moisture",
    fertilizer: "Diluted feed every 4-6 weeks in growth",
    petToxicity: "non-toxic",
    careSummary:
      "Stunning patterned leaves that move with the day. Sensitive to tap water\u2014use filtered or rainwater.",
  },
  {
    commonName: "Philodendron",
    scientificName: "Philodendron hederaceum",
    careDifficulty: "easy",
    light: "Medium to bright indirect",
    water: "Water when top 2cm of soil is dry",
    humidity: "Average to high",
    temperature: "18-27\u00B0C (65-80\u00B0F)",
    soil: "Well-draining houseplant mix",
    fertilizer: "Balanced fertilizer monthly in growth",
    petToxicity: "toxic-pets",
    careSummary:
      "Fast trailer or climber depending on support. Easy to propagate and forgiving of light shifts.",
  },
  {
    commonName: "Anthurium",
    scientificName: "Anthurium andraeanum",
    careDifficulty: "moderate",
    light: "Bright indirect",
    water: "Water when top 2cm of soil is dry",
    humidity: "60% or higher",
    temperature: "18-27\u00B0C (65-80\u00B0F)",
    soil: "Chunky aroid mix",
    fertilizer: "Diluted phosphorus-rich feed for blooms",
    petToxicity: "toxic-pets",
    careSummary:
      "Long-lasting waxy blooms in red, pink, or white. Steady warmth and humidity keep it flowering.",
  },
  {
    commonName: "Orchid",
    scientificName: "Phalaenopsis spp.",
    careDifficulty: "moderate",
    light: "Bright indirect, no harsh sun",
    water: "Soak roots once a week, drain fully",
    humidity: "50-70%",
    temperature: "18-29\u00B0C (65-85\u00B0F)",
    soil: "Bark-based orchid mix",
    fertilizer: "Weak orchid fertilizer every other watering",
    petToxicity: "non-toxic",
    careSummary:
      "Reblooms reliably with bright light and a real dry-down between waterings. Avoid soggy bark.",
  },
  {
    commonName: "Boston Fern",
    scientificName: "Nephrolepis exaltata",
    careDifficulty: "moderate",
    light: "Bright indirect, gentle morning sun",
    water: "Keep consistently moist",
    humidity: "60% or higher",
    temperature: "16-24\u00B0C (60-75\u00B0F)",
    soil: "Peat-rich, moisture-retaining mix",
    fertilizer: "Half-strength balanced feed monthly",
    petToxicity: "non-toxic",
    careSummary:
      "Lush and pet-safe but loves humidity. A bathroom or kitchen with good light is ideal.",
  },
  {
    commonName: "String of Pearls",
    scientificName: "Curio rowleyanus",
    careDifficulty: "moderate",
    light: "Bright indirect with some sun",
    water: "Soak and dry, prone to rot",
    humidity: "Low",
    temperature: "18-24\u00B0C (65-75\u00B0F)",
    soil: "Cactus mix with extra perlite",
    fertilizer: "Light feed in spring and summer",
    petToxicity: "toxic-pets",
    careSummary:
      "Trailing succulent that hates wet roots. Shallow pots and a sunny shelf keep the strands plump.",
  },
  {
    commonName: "Chinese Money Plant",
    scientificName: "Pilea peperomioides",
    careDifficulty: "easy",
    light: "Bright indirect",
    water: "Water when top 2cm of soil is dry",
    humidity: "Average",
    temperature: "16-24\u00B0C (60-75\u00B0F)",
    soil: "Well-draining houseplant mix",
    fertilizer: "Balanced feed monthly in growth season",
    petToxicity: "non-toxic",
    careSummary:
      "Round coin-shaped leaves and quick pup production. Rotate often for an even shape.",
  },
  {
    commonName: "Dracaena",
    scientificName: "Dracaena marginata",
    careDifficulty: "easy",
    light: "Medium to bright indirect",
    water: "Let top half of soil dry between waterings",
    humidity: "Average",
    temperature: "18-27\u00B0C (65-80\u00B0F)",
    soil: "Well-draining houseplant mix",
    fertilizer: "Balanced feed every 2 months in growth",
    petToxicity: "toxic-pets",
    careSummary:
      "Slim sculptural tree. Sensitive to fluoride\u2014use filtered water if leaf tips brown.",
  },
  {
    commonName: "Dieffenbachia",
    scientificName: "Dieffenbachia seguine",
    careDifficulty: "moderate",
    light: "Medium to bright indirect",
    water: "Water when top 2-3cm of soil is dry",
    humidity: "50% or higher",
    temperature: "18-27\u00B0C (65-80\u00B0F)",
    soil: "Rich, well-draining mix",
    fertilizer: "Balanced fertilizer monthly in growth",
    petToxicity: "toxic-pets",
    careSummary:
      "Bold variegated foliage. Wear gloves when pruning\u2014the sap can irritate skin.",
  },
  {
    commonName: "Philodendron Brasil",
    scientificName: "Philodendron hederaceum 'Brasil'",
    careDifficulty: "easy",
    light: "Medium to bright indirect",
    water: "Water when top 2-3cm of soil is dry",
    humidity: "Average to high",
    temperature: "18-27°C (65-80°F)",
    soil: "Well-draining aroid mix",
    fertilizer: "Balanced fertilizer monthly in growth",
    petToxicity: "toxic-pets",
    careSummary:
      "Lime-and-green variegated trailer. Brighter light keeps the splashy variegation bold.",
  },
  {
    commonName: "Philodendron Birkin",
    scientificName: "Philodendron 'Birkin'",
    careDifficulty: "moderate",
    light: "Bright indirect",
    water: "Water when top 2-3cm of soil is dry",
    humidity: "50% or higher",
    temperature: "18-27°C (65-80°F)",
    soil: "Chunky aroid mix",
    fertilizer: "Balanced fertilizer monthly in growth",
    petToxicity: "toxic-pets",
    careSummary:
      "White pinstriped leaves on a compact plant. Needs steady bright light to keep its stripes.",
  },
  {
    commonName: "Philodendron Micans",
    scientificName: "Philodendron hederaceum var. micans",
    careDifficulty: "easy",
    light: "Medium to bright indirect",
    water: "Water when top 2cm of soil is dry",
    humidity: "Average to high",
    temperature: "18-27°C (65-80°F)",
    soil: "Well-draining aroid mix",
    fertilizer: "Balanced fertilizer monthly in growth",
    petToxicity: "toxic-pets",
    careSummary:
      "Velvety heart-shaped leaves with a bronze sheen. Trails beautifully from a shelf.",
  },
  {
    commonName: "Heartleaf Philodendron",
    scientificName: "Philodendron hederaceum",
    careDifficulty: "easy",
    light: "Low to bright indirect",
    water: "Water when top 2cm of soil is dry",
    humidity: "Average",
    temperature: "18-27°C (65-80°F)",
    soil: "Standard houseplant mix",
    fertilizer: "Balanced fertilizer monthly in growth",
    petToxicity: "toxic-pets",
    careSummary:
      "One of the most forgiving vines around. Tolerates low light and the odd missed watering.",
  },
  {
    commonName: "Philodendron Hope Selloum",
    scientificName: "Thaumatophyllum bipinnatifidum",
    careDifficulty: "easy",
    light: "Bright indirect",
    water: "Water when top 3cm of soil is dry",
    humidity: "Average to high",
    temperature: "18-27°C (65-80°F)",
    soil: "Rich, well-draining mix",
    fertilizer: "Balanced fertilizer monthly in growth",
    petToxicity: "toxic-pets",
    careSummary:
      "Big, deeply lobed leaves that fill a corner. Give it room to spread out.",
  },
  {
    commonName: "Monstera Adansonii",
    scientificName: "Monstera adansonii",
    careDifficulty: "easy",
    light: "Bright indirect",
    water: "Water when top 2-3cm of soil is dry",
    humidity: "60% or higher",
    temperature: "18-27°C (65-80°F)",
    soil: "Chunky aroid mix with bark",
    fertilizer: "Balanced fertilizer monthly in growth",
    petToxicity: "toxic-pets",
    careSummary:
      "Swiss cheese vine with lacy holes. Climbs a pole or trails — humidity makes the holes bigger.",
  },
  {
    commonName: "Mini Monstera",
    scientificName: "Rhaphidophora tetrasperma",
    careDifficulty: "easy",
    light: "Bright indirect",
    water: "Water when top 2-3cm of soil is dry",
    humidity: "50% or higher",
    temperature: "18-27°C (65-80°F)",
    soil: "Chunky aroid mix",
    fertilizer: "Balanced fertilizer monthly in growth",
    petToxicity: "toxic-pets",
    careSummary:
      "Fast-growing climber with split leaves. Give it a moss pole and it takes off.",
  },
  {
    commonName: "Marble Queen Pothos",
    scientificName: "Epipremnum aureum 'Marble Queen'",
    careDifficulty: "easy",
    light: "Medium to bright indirect",
    water: "Water when soil is half dry",
    humidity: "Average",
    temperature: "16-29°C (60-85°F)",
    soil: "Standard houseplant mix",
    fertilizer: "Diluted balanced fertilizer every 4-6 weeks",
    petToxicity: "toxic-pets",
    careSummary:
      "Heavily marbled white-and-green pothos. Brighter light keeps the cream variegation strong.",
  },
  {
    commonName: "Neon Pothos",
    scientificName: "Epipremnum aureum 'Neon'",
    careDifficulty: "easy",
    light: "Medium to bright indirect",
    water: "Water when soil is half dry",
    humidity: "Average",
    temperature: "16-29°C (60-85°F)",
    soil: "Standard houseplant mix",
    fertilizer: "Diluted balanced fertilizer every 4-6 weeks",
    petToxicity: "toxic-pets",
    careSummary:
      "Glowing chartreuse leaves that brighten a dim corner. As bulletproof as classic pothos.",
  },
  {
    commonName: "Satin Pothos",
    scientificName: "Scindapsus pictus",
    careDifficulty: "easy",
    light: "Medium to bright indirect",
    water: "Water when top 2-3cm of soil is dry",
    humidity: "Average to high",
    temperature: "18-27°C (65-80°F)",
    soil: "Well-draining aroid mix",
    fertilizer: "Balanced fertilizer monthly in growth",
    petToxicity: "toxic-pets",
    careSummary:
      "Silvery-spotted, satin-textured leaves. Trails elegantly and shrugs off neglect.",
  },
  {
    commonName: "Arrowhead Plant",
    scientificName: "Syngonium podophyllum",
    careDifficulty: "easy",
    light: "Medium to bright indirect",
    water: "Water when top 2cm of soil is dry",
    humidity: "Average to high",
    temperature: "18-27°C (65-80°F)",
    soil: "Well-draining houseplant mix",
    fertilizer: "Balanced fertilizer monthly in growth",
    petToxicity: "toxic-pets",
    careSummary:
      "Shifts from arrow-shaped juvenile leaves to a climbing vine. Comes in green, pink, and white.",
  },
  {
    commonName: "Chinese Evergreen",
    scientificName: "Aglaonema commutatum",
    careDifficulty: "easy",
    light: "Low to medium indirect",
    water: "Water when top 2-3cm of soil is dry",
    humidity: "Average",
    temperature: "18-27°C (65-80°F)",
    soil: "Well-draining houseplant mix",
    fertilizer: "Balanced fertilizer every 6 weeks in growth",
    petToxicity: "toxic-pets",
    careSummary:
      "Colorful, low-light tolerant foliage. Keep it warm and away from cold drafts.",
  },
  {
    commonName: "Alocasia Polly",
    scientificName: "Alocasia × amazonica 'Polly'",
    careDifficulty: "hard",
    light: "Bright indirect, no direct sun",
    water: "Keep lightly moist, never soggy",
    humidity: "60% or higher",
    temperature: "18-27°C (65-80°F)",
    soil: "Airy, well-draining aroid mix",
    fertilizer: "Diluted feed every 4 weeks in growth",
    petToxicity: "toxic-pets",
    careSummary:
      "Dramatic arrow leaves with bold veins. Fussy about humidity and prone to dormancy in winter.",
  },
  {
    commonName: "Alocasia Zebrina",
    scientificName: "Alocasia zebrina",
    careDifficulty: "hard",
    light: "Bright indirect",
    water: "Keep lightly moist, let top dry slightly",
    humidity: "60% or higher",
    temperature: "18-27°C (65-80°F)",
    soil: "Airy, well-draining aroid mix",
    fertilizer: "Diluted feed every 4 weeks in growth",
    petToxicity: "toxic-pets",
    careSummary:
      "Striking zebra-striped stems hold up arrow leaves. Loves humidity and bright, filtered light.",
  },
  {
    commonName: "Caladium",
    scientificName: "Caladium bicolor",
    careDifficulty: "moderate",
    light: "Bright indirect",
    water: "Keep evenly moist during growth",
    humidity: "60% or higher",
    temperature: "18-27°C (65-80°F)",
    soil: "Rich, moisture-retaining mix",
    fertilizer: "Balanced feed every 2-4 weeks in growth",
    petToxicity: "toxic-pets",
    careSummary:
      "Paper-thin heart leaves in pink, red, and white. Goes dormant from a tuber in cooler months.",
  },
  {
    commonName: "Bird's Nest Fern",
    scientificName: "Asplenium nidus",
    careDifficulty: "easy",
    light: "Medium indirect",
    water: "Keep evenly moist, water around the crown",
    humidity: "60% or higher",
    temperature: "18-27°C (65-80°F)",
    soil: "Peaty, moisture-retaining mix",
    fertilizer: "Half-strength feed monthly in growth",
    petToxicity: "non-toxic",
    careSummary:
      "Glossy ripple-edged fronds and pet-safe. Avoid pouring water into the center of the nest.",
  },
  {
    commonName: "Maidenhair Fern",
    scientificName: "Adiantum raddianum",
    careDifficulty: "hard",
    light: "Medium indirect, no direct sun",
    water: "Keep consistently moist at all times",
    humidity: "70% or higher",
    temperature: "16-24°C (60-75°F)",
    soil: "Peaty, moisture-retaining mix",
    fertilizer: "Quarter-strength feed monthly",
    petToxicity: "non-toxic",
    careSummary:
      "Delicate, lacy fronds that crisp the moment they dry out. Best in a humid bathroom.",
  },
  {
    commonName: "Staghorn Fern",
    scientificName: "Platycerium bifurcatum",
    careDifficulty: "moderate",
    light: "Bright indirect",
    water: "Soak weekly, let it drain well",
    humidity: "Average to high",
    temperature: "16-27°C (60-80°F)",
    soil: "Mounted on bark or in sphagnum moss",
    fertilizer: "Diluted feed monthly in growth",
    petToxicity: "non-toxic",
    careSummary:
      "Antler-shaped fronds, often mounted on a board. Water by soaking the moss, then let it dry.",
  },
  {
    commonName: "Kimberly Queen Fern",
    scientificName: "Nephrolepis obliterata",
    careDifficulty: "moderate",
    light: "Bright indirect",
    water: "Keep consistently moist",
    humidity: "50% or higher",
    temperature: "16-24°C (60-75°F)",
    soil: "Peat-rich, moisture-retaining mix",
    fertilizer: "Half-strength feed monthly in growth",
    petToxicity: "non-toxic",
    careSummary:
      "Upright, tidy cousin of the Boston fern. Less messy and a touch more forgiving.",
  },
  {
    commonName: "Blue Star Fern",
    scientificName: "Phlebodium aureum",
    careDifficulty: "easy",
    light: "Medium indirect",
    water: "Water when top 2cm of soil is dry",
    humidity: "50% or higher",
    temperature: "16-24°C (60-75°F)",
    soil: "Airy, bark-and-peat mix",
    fertilizer: "Half-strength feed monthly in growth",
    petToxicity: "non-toxic",
    careSummary:
      "Blue-green wavy fronds and unusually easygoing for a fern. Tolerates a little dry-down.",
  },
  {
    commonName: "Calathea Medallion",
    scientificName: "Goeppertia veitchiana",
    careDifficulty: "hard",
    light: "Medium indirect, no direct sun",
    water: "Keep evenly moist with filtered water",
    humidity: "60% or higher",
    temperature: "18-27°C (65-80°F)",
    soil: "Peat-based, moisture-retaining mix",
    fertilizer: "Diluted feed every 4-6 weeks in growth",
    petToxicity: "non-toxic",
    careSummary:
      "Rounded leaves with a painted feather pattern. Sensitive to tap water — use filtered or rain.",
  },
  {
    commonName: "Rattlesnake Plant",
    scientificName: "Goeppertia insignis",
    careDifficulty: "hard",
    light: "Medium indirect",
    water: "Keep evenly moist with filtered water",
    humidity: "60% or higher",
    temperature: "18-27°C (65-80°F)",
    soil: "Peat-based, moisture-retaining mix",
    fertilizer: "Diluted feed every 4-6 weeks in growth",
    petToxicity: "non-toxic",
    careSummary:
      "Wavy leaves with dark spots and purple undersides. Pet-safe but demands humidity and clean water.",
  },
  {
    commonName: "Prayer Plant",
    scientificName: "Maranta leuconeura",
    careDifficulty: "moderate",
    light: "Medium indirect",
    water: "Keep evenly moist with filtered water",
    humidity: "60% or higher",
    temperature: "18-27°C (65-80°F)",
    soil: "Peat-based, moisture-retaining mix",
    fertilizer: "Diluted feed every 4 weeks in growth",
    petToxicity: "non-toxic",
    careSummary:
      "Folds its patterned leaves up at night like praying hands. Loves humidity and pet-safe.",
  },
  {
    commonName: "Stromanthe Triostar",
    scientificName: "Stromanthe sanguinea 'Triostar'",
    careDifficulty: "hard",
    light: "Bright indirect",
    water: "Keep evenly moist with filtered water",
    humidity: "60% or higher",
    temperature: "18-27°C (65-80°F)",
    soil: "Peat-based, moisture-retaining mix",
    fertilizer: "Diluted feed every 4-6 weeks in growth",
    petToxicity: "non-toxic",
    careSummary:
      "Pink, cream, and green leaves with magenta undersides. Stunning but thirsty for humidity.",
  },
  {
    commonName: "Echeveria",
    scientificName: "Echeveria elegans",
    careDifficulty: "easy",
    light: "Bright direct light",
    water: "Soak and fully dry between waterings",
    humidity: "Low",
    temperature: "15-27°C (59-80°F)",
    soil: "Gritty cactus and succulent mix",
    fertilizer: "Diluted cactus feed in spring/summer",
    petToxicity: "non-toxic",
    careSummary:
      "Classic rosette succulent and pet-safe. Plenty of sun keeps it tight and colorful.",
  },
  {
    commonName: "Zebra Haworthia",
    scientificName: "Haworthiopsis fasciata",
    careDifficulty: "easy",
    light: "Bright indirect to some direct",
    water: "Soak and dry; very drought tolerant",
    humidity: "Low",
    temperature: "15-27°C (59-80°F)",
    soil: "Gritty cactus and succulent mix",
    fertilizer: "Light cactus feed in spring",
    petToxicity: "non-toxic",
    careSummary:
      "Small white-striped rosette, perfect for a sunny desk. Pet-safe and nearly indestructible.",
  },
  {
    commonName: "Burro's Tail",
    scientificName: "Sedum morganianum",
    careDifficulty: "easy",
    light: "Bright direct or strong indirect",
    water: "Soak and fully dry; very drought tolerant",
    humidity: "Low",
    temperature: "16-27°C (60-80°F)",
    soil: "Gritty cactus and succulent mix",
    fertilizer: "Light cactus feed in spring/summer",
    petToxicity: "non-toxic",
    careSummary:
      "Trailing strands of plump blue-green beads. Handle gently — the leaves drop at a touch.",
  },
  {
    commonName: "String of Hearts",
    scientificName: "Ceropegia woodii",
    careDifficulty: "easy",
    light: "Bright indirect with some sun",
    water: "Soak and dry; tubers store water",
    humidity: "Low to average",
    temperature: "16-26°C (60-79°F)",
    soil: "Cactus mix with extra perlite",
    fertilizer: "Light feed in spring and summer",
    petToxicity: "non-toxic",
    careSummary:
      "Dainty heart-shaped leaves on long trailing vines. Pet-safe and very drought tolerant.",
  },
  {
    commonName: "String of Bananas",
    scientificName: "Curio radicans",
    careDifficulty: "easy",
    light: "Bright indirect with some sun",
    water: "Soak and dry; drought tolerant",
    humidity: "Low",
    temperature: "18-26°C (65-79°F)",
    soil: "Cactus mix with extra perlite",
    fertilizer: "Light feed in spring and summer",
    petToxicity: "toxic-pets",
    careSummary:
      "Faster and more forgiving than string of pearls. Banana-shaped beads trail vigorously.",
  },
  {
    commonName: "Christmas Cactus",
    scientificName: "Schlumbergera bridgesii",
    careDifficulty: "easy",
    light: "Bright indirect",
    water: "Water when top 2cm of soil is dry",
    humidity: "Average to high",
    temperature: "16-24°C (60-75°F)",
    soil: "Well-draining mix with some bark",
    fertilizer: "Diluted feed monthly in spring/summer",
    petToxicity: "non-toxic",
    careSummary:
      "Pet-safe holiday bloomer. Cool nights and shorter days trigger its winter flowers.",
  },
  {
    commonName: "Panda Plant",
    scientificName: "Kalanchoe tomentosa",
    careDifficulty: "easy",
    light: "Bright indirect to some direct",
    water: "Soak and fully dry between waterings",
    humidity: "Low",
    temperature: "16-27°C (60-80°F)",
    soil: "Gritty cactus and succulent mix",
    fertilizer: "Light cactus feed in spring/summer",
    petToxicity: "toxic-pets",
    careSummary:
      "Fuzzy silver leaves edged in brown. Avoid getting water on the velvety foliage.",
  },
  {
    commonName: "Flaming Katy",
    scientificName: "Kalanchoe blossfeldiana",
    careDifficulty: "easy",
    light: "Bright indirect to some direct",
    water: "Soak and dry between waterings",
    humidity: "Low to average",
    temperature: "16-27°C (60-80°F)",
    soil: "Well-draining succulent mix",
    fertilizer: "Diluted feed monthly while blooming",
    petToxicity: "toxic-pets",
    careSummary:
      "Long-lasting clusters of bright blooms. Treat the leaves like a succulent and give it sun.",
  },
  {
    commonName: "Golden Barrel Cactus",
    scientificName: "Echinocactus grusonii",
    careDifficulty: "easy",
    light: "Bright direct light",
    water: "Soak sparingly, dry out completely",
    humidity: "Low",
    temperature: "16-29°C (60-85°F)",
    soil: "Gritty cactus mix",
    fertilizer: "Light cactus feed in spring/summer",
    petToxicity: "non-toxic",
    careSummary:
      "Round, golden-spined desert cactus. Wants the brightest spot and very little water.",
  },
  {
    commonName: "Bunny Ear Cactus",
    scientificName: "Opuntia microdasys",
    careDifficulty: "easy",
    light: "Bright direct light",
    water: "Soak sparingly, dry out completely",
    humidity: "Low",
    temperature: "16-29°C (60-85°F)",
    soil: "Gritty cactus mix",
    fertilizer: "Light cactus feed in spring/summer",
    petToxicity: "non-toxic",
    careSummary:
      "Pads dotted with tufts of fine prickles — handle with care. Loves heat and full sun.",
  },
  {
    commonName: "Weeping Fig",
    scientificName: "Ficus benjamina",
    careDifficulty: "moderate",
    light: "Bright indirect",
    water: "Water when top 2-3cm of soil is dry",
    humidity: "Average to high",
    temperature: "16-24°C (60-75°F)",
    soil: "Well-draining mix",
    fertilizer: "Balanced feed monthly in growth",
    petToxicity: "toxic-pets",
    careSummary:
      "Graceful tree that drops leaves when moved or stressed. Pick a bright spot and leave it put.",
  },
  {
    commonName: "Ficus Audrey",
    scientificName: "Ficus benghalensis",
    careDifficulty: "moderate",
    light: "Bright indirect, some direct sun",
    water: "Water when top 3cm of soil is dry",
    humidity: "Average to high",
    temperature: "18-24°C (65-75°F)",
    soil: "Well-draining loam mix",
    fertilizer: "Balanced feed monthly in growth",
    petToxicity: "toxic-pets",
    careSummary:
      "Velvety leaves and a sturdier temperament than the fiddle leaf fig. Loves bright, steady light.",
  },
  {
    commonName: "Areca Palm",
    scientificName: "Dypsis lutescens",
    careDifficulty: "moderate",
    light: "Bright indirect",
    water: "Keep lightly moist, let top dry slightly",
    humidity: "50% or higher",
    temperature: "18-27°C (65-80°F)",
    soil: "Well-draining peaty mix",
    fertilizer: "Balanced feed monthly in growth",
    petToxicity: "non-toxic",
    careSummary:
      "Feathery, pet-safe palm that adds a tropical feel. Sensitive to fluoride — use filtered water.",
  },
  {
    commonName: "Parlor Palm",
    scientificName: "Chamaedorea elegans",
    careDifficulty: "easy",
    light: "Low to medium indirect",
    water: "Water when top 2-3cm of soil is dry",
    humidity: "Average",
    temperature: "18-27°C (65-80°F)",
    soil: "Well-draining houseplant mix",
    fertilizer: "Half-strength feed every 2 months",
    petToxicity: "non-toxic",
    careSummary:
      "Pet-safe palm that handles low light better than most. Easy and slow-growing.",
  },
  {
    commonName: "Ponytail Palm",
    scientificName: "Beaucarnea recurvata",
    careDifficulty: "easy",
    light: "Bright indirect to direct",
    water: "Soak, then let dry; stores water in base",
    humidity: "Low",
    temperature: "16-27°C (60-80°F)",
    soil: "Cactus or succulent mix",
    fertilizer: "Light feed in spring/summer",
    petToxicity: "non-toxic",
    careSummary:
      "Not a true palm — a drought-tolerant succulent with a swollen base. Under-water rather than over.",
  },
  {
    commonName: "Majesty Palm",
    scientificName: "Ravenea rivularis",
    careDifficulty: "moderate",
    light: "Bright indirect, some direct sun",
    water: "Keep consistently moist",
    humidity: "50% or higher",
    temperature: "18-27°C (65-80°F)",
    soil: "Rich, moisture-retaining mix",
    fertilizer: "Balanced feed monthly in growth",
    petToxicity: "non-toxic",
    careSummary:
      "Lush, pet-safe floor palm that drinks a lot. Browning tips usually mean more water or humidity.",
  },
  {
    commonName: "Kentia Palm",
    scientificName: "Howea forsteriana",
    careDifficulty: "easy",
    light: "Medium to bright indirect",
    water: "Water when top 3cm of soil is dry",
    humidity: "Average",
    temperature: "18-27°C (65-80°F)",
    soil: "Well-draining houseplant mix",
    fertilizer: "Balanced feed every 6 weeks in growth",
    petToxicity: "non-toxic",
    careSummary:
      "Elegant, pet-safe palm that tolerates lower light and the odd dry spell. A classic indoor tree.",
  },
  {
    commonName: "Sago Palm",
    scientificName: "Cycas revoluta",
    careDifficulty: "moderate",
    light: "Bright indirect to some direct",
    water: "Water when top half of soil is dry",
    humidity: "Average",
    temperature: "16-27°C (60-80°F)",
    soil: "Well-draining sandy mix",
    fertilizer: "Light feed twice in growing season",
    petToxicity: "toxic-all",
    careSummary:
      "Not a true palm and HIGHLY toxic if eaten — keep away from pets and children. Slow and sculptural.",
  },
  {
    commonName: "Corn Plant",
    scientificName: "Dracaena fragrans",
    careDifficulty: "easy",
    light: "Medium to bright indirect",
    water: "Let top half of soil dry between waterings",
    humidity: "Average",
    temperature: "18-27°C (65-80°F)",
    soil: "Well-draining houseplant mix",
    fertilizer: "Balanced feed every 2 months in growth",
    petToxicity: "toxic-pets",
    careSummary:
      "Tall cane with arching striped leaves. Sensitive to fluoride — use filtered water for clean tips.",
  },
  {
    commonName: "Lucky Bamboo",
    scientificName: "Dracaena sanderiana",
    careDifficulty: "easy",
    light: "Medium indirect, no direct sun",
    water: "Grow in water or keep soil moist",
    humidity: "Average",
    temperature: "18-27°C (65-80°F)",
    soil: "Water with pebbles, or light potting mix",
    fertilizer: "Very diluted feed every 1-2 months",
    petToxicity: "toxic-pets",
    careSummary:
      "Often grown in water — change it weekly and use filtered to avoid tip burn. Tolerates low light.",
  },
  {
    commonName: "Hoya Carnosa",
    scientificName: "Hoya carnosa",
    careDifficulty: "easy",
    light: "Bright indirect with some sun",
    water: "Water when top 3cm of soil is dry",
    humidity: "Average to high",
    temperature: "18-27°C (65-80°F)",
    soil: "Chunky, well-draining mix",
    fertilizer: "Diluted feed monthly in growth",
    petToxicity: "non-toxic",
    careSummary:
      "Waxy-leaved vine with fragrant star flowers. Pet-safe; don't cut off the bloom spurs.",
  },
  {
    commonName: "Sweetheart Hoya",
    scientificName: "Hoya kerrii",
    careDifficulty: "easy",
    light: "Bright indirect",
    water: "Soak and dry; stores water in the leaf",
    humidity: "Average",
    temperature: "18-27°C (65-80°F)",
    soil: "Chunky, well-draining mix",
    fertilizer: "Diluted feed every 6 weeks in growth",
    petToxicity: "non-toxic",
    careSummary:
      "The single heart-leaf cutting is popular as a gift. A full vine needs patience and bright light.",
  },
  {
    commonName: "English Ivy",
    scientificName: "Hedera helix",
    careDifficulty: "moderate",
    light: "Bright indirect",
    water: "Water when top 2cm of soil is dry",
    humidity: "Average to high",
    temperature: "13-21°C (55-70°F)",
    soil: "Well-draining houseplant mix",
    fertilizer: "Balanced feed monthly in growth",
    petToxicity: "toxic-pets",
    careSummary:
      "Classic trailing or climbing ivy. Prefers cooler rooms and good airflow to deter spider mites.",
  },
  {
    commonName: "Inch Plant",
    scientificName: "Tradescantia zebrina",
    careDifficulty: "easy",
    light: "Bright indirect with some sun",
    water: "Water when top 2cm of soil is dry",
    humidity: "Average",
    temperature: "16-27°C (60-80°F)",
    soil: "Standard houseplant mix",
    fertilizer: "Balanced feed monthly in growth",
    petToxicity: "toxic-pets",
    careSummary:
      "Fast-growing purple-and-silver trailer. Pinch it back often to keep it full, not leggy.",
  },
  {
    commonName: "Watermelon Peperomia",
    scientificName: "Peperomia argyreia",
    careDifficulty: "easy",
    light: "Medium to bright indirect",
    water: "Water when top 2-3cm of soil is dry",
    humidity: "Average",
    temperature: "18-26°C (65-79°F)",
    soil: "Light, well-draining mix",
    fertilizer: "Diluted feed every 6 weeks in growth",
    petToxicity: "non-toxic",
    careSummary:
      "Round leaves striped like watermelon rind. Pet-safe and stores water, so don't overwater.",
  },
  {
    commonName: "Baby Rubber Plant",
    scientificName: "Peperomia obtusifolia",
    careDifficulty: "easy",
    light: "Medium to bright indirect",
    water: "Water when top 2-3cm of soil is dry",
    humidity: "Average",
    temperature: "18-26°C (65-79°F)",
    soil: "Light, well-draining mix",
    fertilizer: "Diluted feed every 6 weeks in growth",
    petToxicity: "non-toxic",
    careSummary:
      "Thick, glossy leaves on a compact, pet-safe plant. Semi-succulent — let it dry between drinks.",
  },
  {
    commonName: "String of Turtles",
    scientificName: "Peperomia prostrata",
    careDifficulty: "moderate",
    light: "Bright indirect",
    water: "Water when top 2cm of soil is dry",
    humidity: "Average to high",
    temperature: "18-26°C (65-79°F)",
    soil: "Light, well-draining mix",
    fertilizer: "Diluted feed every 6 weeks in growth",
    petToxicity: "non-toxic",
    careSummary:
      "Tiny turtle-shell leaves on a delicate trailer. Pet-safe; bright light keeps the pattern crisp.",
  },
  {
    commonName: "African Violet",
    scientificName: "Saintpaulia ionantha",
    careDifficulty: "moderate",
    light: "Bright indirect",
    water: "Keep lightly moist, water from below",
    humidity: "Average to high",
    temperature: "18-24°C (65-75°F)",
    soil: "Light African violet mix",
    fertilizer: "Violet fertilizer every 2 weeks in bloom",
    petToxicity: "non-toxic",
    careSummary:
      "Blooms year-round in good light. Pet-safe; avoid splashing the fuzzy leaves with cold water.",
  },
  {
    commonName: "Bromeliad",
    scientificName: "Guzmania lingulata",
    careDifficulty: "easy",
    light: "Bright indirect",
    water: "Keep the central cup filled with water",
    humidity: "50% or higher",
    temperature: "18-27°C (65-80°F)",
    soil: "Airy, orchid-style bark mix",
    fertilizer: "Very diluted feed monthly in growth",
    petToxicity: "non-toxic",
    careSummary:
      "Vivid, long-lasting bloom and pet-safe. Water into the central cup and flush it occasionally.",
  },
  {
    commonName: "Polka Dot Begonia",
    scientificName: "Begonia maculata",
    careDifficulty: "moderate",
    light: "Bright indirect",
    water: "Water when top 2-3cm of soil is dry",
    humidity: "50% or higher",
    temperature: "18-27°C (65-80°F)",
    soil: "Light, well-draining mix",
    fertilizer: "Balanced feed every 4 weeks in growth",
    petToxicity: "toxic-pets",
    careSummary:
      "Angel-wing leaves spotted silver with red undersides. Wants humidity but hates soggy roots.",
  },
  {
    commonName: "Rex Begonia",
    scientificName: "Begonia rex-cultorum",
    careDifficulty: "moderate",
    light: "Bright indirect, no direct sun",
    water: "Keep lightly moist, avoid wet leaves",
    humidity: "50% or higher",
    temperature: "18-24°C (65-75°F)",
    soil: "Light, well-draining mix",
    fertilizer: "Diluted feed every 4 weeks in growth",
    petToxicity: "toxic-pets",
    careSummary:
      "Grown for its swirling, jewel-toned foliage. Loves humidity but rots if kept too wet.",
  },
  {
    commonName: "Nerve Plant",
    scientificName: "Fittonia albivenis",
    careDifficulty: "moderate",
    light: "Medium indirect",
    water: "Keep consistently moist",
    humidity: "60% or higher",
    temperature: "18-27°C (65-80°F)",
    soil: "Peaty, moisture-retaining mix",
    fertilizer: "Diluted feed monthly in growth",
    petToxicity: "non-toxic",
    careSummary:
      "Pink or white veined leaves that dramatically faint when dry — and perk right back up. Pet-safe.",
  },
  {
    commonName: "Polka Dot Plant",
    scientificName: "Hypoestes phyllostachya",
    careDifficulty: "easy",
    light: "Bright indirect",
    water: "Water when top 2cm of soil is dry",
    humidity: "Average to high",
    temperature: "18-27°C (65-80°F)",
    soil: "Light, well-draining mix",
    fertilizer: "Balanced feed monthly in growth",
    petToxicity: "non-toxic",
    careSummary:
      "Freckled pink, red, or white leaves. Pet-safe; pinch the tips to keep it bushy.",
  },
  {
    commonName: "Money Tree",
    scientificName: "Pachira aquatica",
    careDifficulty: "easy",
    light: "Bright indirect",
    water: "Water when top 3-5cm of soil is dry",
    humidity: "Average to high",
    temperature: "18-27°C (65-80°F)",
    soil: "Well-draining houseplant mix",
    fertilizer: "Balanced feed monthly in growth",
    petToxicity: "non-toxic",
    careSummary:
      "Braided-trunk tree said to bring luck. Pet-safe and forgiving — just don't keep it soggy.",
  },
  {
    commonName: "Croton",
    scientificName: "Codiaeum variegatum",
    careDifficulty: "moderate",
    light: "Bright indirect, some direct sun",
    water: "Water when top 2cm of soil is dry",
    humidity: "50% or higher",
    temperature: "18-27°C (65-80°F)",
    soil: "Rich, well-draining mix",
    fertilizer: "Balanced feed monthly in growth",
    petToxicity: "toxic-pets",
    careSummary:
      "Bold red, orange, and yellow foliage. Needs bright light for color and drops leaves if moved.",
  },
  {
    commonName: "Umbrella Plant",
    scientificName: "Schefflera arboricola",
    careDifficulty: "easy",
    light: "Bright indirect",
    water: "Water when top 2-3cm of soil is dry",
    humidity: "Average",
    temperature: "16-24°C (60-75°F)",
    soil: "Well-draining houseplant mix",
    fertilizer: "Balanced feed monthly in growth",
    petToxicity: "toxic-pets",
    careSummary:
      "Glossy leaflets fan out like umbrella spokes. Fast-growing and tolerant; prune to keep compact.",
  },
  {
    commonName: "Cast Iron Plant",
    scientificName: "Aspidistra elatior",
    careDifficulty: "easy",
    light: "Low to medium indirect",
    water: "Water when top half of soil is dry",
    humidity: "Average",
    temperature: "13-24°C (55-75°F)",
    soil: "Well-draining houseplant mix",
    fertilizer: "Light feed every 2 months in growth",
    petToxicity: "non-toxic",
    careSummary:
      "True to its name — survives low light, neglect, and temperature swings. Pet-safe and slow.",
  },
  {
    commonName: "Bird of Paradise",
    scientificName: "Strelitzia reginae",
    careDifficulty: "moderate",
    light: "Bright direct or strong indirect",
    water: "Water when top 3cm of soil is dry",
    humidity: "Average to high",
    temperature: "18-27°C (65-80°F)",
    soil: "Rich, well-draining mix",
    fertilizer: "Balanced feed monthly in growth",
    petToxicity: "toxic-pets",
    careSummary:
      "Big paddle leaves and a tropical presence. Needs lots of light and a few years to flower indoors.",
  },
  {
    commonName: "Norfolk Island Pine",
    scientificName: "Araucaria heterophylla",
    careDifficulty: "moderate",
    light: "Bright indirect, some direct sun",
    water: "Keep lightly moist, let top dry slightly",
    humidity: "50% or higher",
    temperature: "16-24°C (60-75°F)",
    soil: "Well-draining mix with peat",
    fertilizer: "Half-strength feed monthly in growth",
    petToxicity: "toxic-pets",
    careSummary:
      "A soft, living mini conifer. Loves bright light and humidity; brown branches won't regrow.",
  },
  {
    commonName: "Air Plant",
    scientificName: "Tillandsia spp.",
    careDifficulty: "easy",
    light: "Bright indirect",
    water: "Soak 20-30 min weekly, dry fully",
    humidity: "Average to high",
    temperature: "16-27°C (60-80°F)",
    soil: "None — grows without soil",
    fertilizer: "Bromeliad feed in the soak monthly",
    petToxicity: "non-toxic",
    careSummary:
      "Lives without soil — soak weekly, shake off excess, and let it dry fully to avoid rot. Pet-safe.",
  },
  {
    commonName: "Coffee Plant",
    scientificName: "Coffea arabica",
    careDifficulty: "moderate",
    light: "Bright indirect",
    water: "Keep evenly moist, never soggy",
    humidity: "50% or higher",
    temperature: "18-26°C (65-79°F)",
    soil: "Rich, slightly acidic well-draining mix",
    fertilizer: "Balanced feed monthly in growth",
    petToxicity: "toxic-pets",
    careSummary:
      "Glossy leaves and, eventually, real coffee cherries. Keep humidity up and water consistent.",
  },
  {
    commonName: "Oxalis",
    scientificName: "Oxalis triangularis",
    careDifficulty: "easy",
    light: "Bright indirect with some sun",
    water: "Water when top 2cm of soil is dry",
    humidity: "Average",
    temperature: "16-24°C (60-75°F)",
    soil: "Well-draining houseplant mix",
    fertilizer: "Balanced feed monthly in growth",
    petToxicity: "toxic-pets",
    careSummary:
      "Purple shamrock leaves that fold at night. Goes dormant from bulbs, then returns — don't toss it.",
  },
  {
    commonName: "Ti Plant",
    scientificName: "Cordyline fruticosa",
    careDifficulty: "moderate",
    light: "Bright indirect, some direct sun",
    water: "Keep lightly moist with filtered water",
    humidity: "50% or higher",
    temperature: "18-27°C (65-80°F)",
    soil: "Rich, well-draining mix",
    fertilizer: "Balanced feed monthly in growth",
    petToxicity: "toxic-pets",
    careSummary:
      "Vivid pink-and-burgundy strappy leaves. Sensitive to fluoride — filtered water keeps tips clean.",
  },
  {
    commonName: "Yucca",
    scientificName: "Yucca elephantipes",
    careDifficulty: "easy",
    light: "Bright direct or strong indirect",
    water: "Soak, then let dry well; drought tolerant",
    humidity: "Low",
    temperature: "16-27°C (60-80°F)",
    soil: "Well-draining sandy mix",
    fertilizer: "Light feed in spring/summer",
    petToxicity: "toxic-pets",
    careSummary:
      "Sword-shaped leaves on a sturdy cane. Loves sun and dry soil; overwatering is the only real risk.",
  },
  {
    commonName: "Purple Heart",
    scientificName: "Tradescantia pallida",
    careDifficulty: "easy",
    light: "Bright direct or strong indirect",
    water: "Water when top 2cm of soil is dry",
    humidity: "Average",
    temperature: "16-27°C (60-80°F)",
    soil: "Standard houseplant mix",
    fertilizer: "Balanced feed monthly in growth",
    petToxicity: "toxic-pets",
    careSummary:
      "Deep purple, fast-spreading trailer. The brighter the light, the richer the color.",
  },
  {
    commonName: "Succulent Mix",
    scientificName: null,
    careDifficulty: "easy",
    light: "Bright direct or strong indirect",
    water: "Soak and fully dry between waterings",
    humidity: "Low",
    temperature: "13-27\u00B0C (55-80\u00B0F)",
    soil: "Gritty cactus and succulent mix",
    fertilizer: "Diluted cactus fertilizer in spring/summer",
    petToxicity: "unknown",
    careSummary:
      "Mixed planters of small succulents. Track each variety separately as you learn what each prefers.",
  },
];
