import type { PlantPresetInsertInput } from "@/lib/db/zod";

export const builtInPlantPresets: ReadonlyArray<PlantPresetInsertInput> = [
  {
    commonName: "Monstera",
    scientificName: "Monstera deliciosa",
    careDifficulty: "easy",
    light: "Bright indirect light",
    water: "Water when top 2-3cm of soil is dry",
    humidity: "50% or higher",
    temperature: "18-27\u00B0C (65-80\u00B0F)",
    soil: "Well-draining aroid mix with bark and perlite",
    fertilizer: "Balanced liquid fertilizer monthly during growth",
    petToxicity: "toxic-pets",
    careSummary:
      "Forgiving climber that loves a moss pole. Wipe the big leaves and let the soil dry between waterings.",
  },
  {
    commonName: "Pothos",
    scientificName: "Epipremnum aureum",
    careDifficulty: "easy",
    light: "Low to bright indirect",
    water: "Water when soil is half dry",
    humidity: "Average household humidity",
    temperature: "16-29\u00B0C (60-85\u00B0F)",
    soil: "Standard houseplant mix",
    fertilizer: "Diluted balanced fertilizer every 4-6 weeks",
    petToxicity: "toxic-pets",
    careSummary:
      "Bulletproof trailing vine. Tolerates low light, neglect, and is easy to propagate from cuttings.",
  },
  {
    commonName: "Snake Plant",
    scientificName: "Dracaena trifasciata",
    careDifficulty: "easy",
    light: "Low to bright indirect",
    water: "Let soil dry completely between waterings",
    humidity: "Tolerates dry air",
    temperature: "15-29\u00B0C (60-85\u00B0F)",
    soil: "Cactus or succulent mix",
    fertilizer: "Light feed twice per growing season",
    petToxicity: "toxic-pets",
    careSummary:
      "Architectural and forgiving. Overwatering is the only real risk\u2014keep it on the dry side.",
  },
  {
    commonName: "Peace Lily",
    scientificName: "Spathiphyllum wallisii",
    careDifficulty: "moderate",
    light: "Medium indirect, tolerates low",
    water: "Keep evenly moist, droops when thirsty",
    humidity: "50% or higher preferred",
    temperature: "18-27\u00B0C (65-80\u00B0F)",
    soil: "Rich, well-draining houseplant mix",
    fertilizer: "Balanced fertilizer every 6 weeks",
    petToxicity: "toxic-pets",
    careSummary:
      "Drama queen that bounces back fast. The leaf droop is a clear cue it needs water.",
  },
  {
    commonName: "ZZ Plant",
    scientificName: "Zamioculcas zamiifolia",
    careDifficulty: "easy",
    light: "Low to bright indirect",
    water: "Water sparingly, every 2-3 weeks",
    humidity: "Tolerates dry air",
    temperature: "18-26\u00B0C (65-79\u00B0F)",
    soil: "Well-draining mix with perlite",
    fertilizer: "Light feed every 2 months in growth season",
    petToxicity: "toxic-pets",
    careSummary:
      "Stores water in its rhizomes, so under-water rather than over-water. Slow but indestructible.",
  },
  {
    commonName: "Spider Plant",
    scientificName: "Chlorophytum comosum",
    careDifficulty: "easy",
    light: "Bright indirect",
    water: "Water when top 2cm of soil is dry",
    humidity: "Average",
    temperature: "13-27\u00B0C (55-80\u00B0F)",
    soil: "Standard houseplant mix",
    fertilizer: "Balanced fertilizer monthly in spring/summer",
    petToxicity: "non-toxic",
    careSummary:
      "Pet-safe and prolific. Produces baby plantlets that root quickly in water or soil.",
  },
  {
    commonName: "Fiddle Leaf Fig",
    scientificName: "Ficus lyrata",
    careDifficulty: "hard",
    light: "Bright indirect, some morning sun",
    water: "Water when top 3-5cm of soil is dry",
    humidity: "50% or higher",
    temperature: "18-24\u00B0C (65-75\u00B0F)",
    soil: "Well-draining loam mix",
    fertilizer: "Monthly during growing season",
    petToxicity: "toxic-pets",
    careSummary:
      "Statement tree that hates being moved. Pick a bright spot and stick with a steady routine.",
  },
  {
    commonName: "Rubber Plant",
    scientificName: "Ficus elastica",
    careDifficulty: "moderate",
    light: "Bright indirect",
    water: "Water when top 2cm of soil is dry",
    humidity: "Average to high",
    temperature: "16-24\u00B0C (60-75\u00B0F)",
    soil: "Well-draining mix",
    fertilizer: "Balanced fertilizer monthly in growth",
    petToxicity: "toxic-pets",
    careSummary:
      "Glossy upright tree with deep burgundy varieties. Wipe leaves regularly so they keep their shine.",
  },
  {
    commonName: "Aloe Vera",
    scientificName: "Aloe barbadensis miller",
    careDifficulty: "easy",
    light: "Bright direct or strong indirect",
    water: "Deep water, then let dry completely",
    humidity: "Low; thrives in dry rooms",
    temperature: "13-27\u00B0C (55-80\u00B0F)",
    soil: "Cactus or succulent mix",
    fertilizer: "Light feed in spring only",
    petToxicity: "toxic-pets",
    careSummary:
      "Useful and tough. Treat like a succulent\u2014lots of light, infrequent water.",
  },
  {
    commonName: "Jade Plant",
    scientificName: "Crassula ovata",
    careDifficulty: "easy",
    light: "Bright direct light",
    water: "Soak and dry; very drought tolerant",
    humidity: "Low",
    temperature: "16-24\u00B0C (60-75\u00B0F)",
    soil: "Cactus or succulent mix",
    fertilizer: "Diluted feed every 2-3 months",
    petToxicity: "toxic-pets",
    careSummary:
      "Slow-growing succulent tree. Stems stay sturdy with bright light and infrequent watering.",
  },
  {
    commonName: "Calathea",
    scientificName: "Goeppertia orbifolia",
    careDifficulty: "hard",
    light: "Medium indirect, no direct sun",
    water: "Keep evenly moist with filtered water",
    humidity: "60% or higher",
    temperature: "18-27\u00B0C (65-80\u00B0F)",
    soil: "Peat-based mix that retains moisture",
    fertilizer: "Diluted feed every 4-6 weeks in growth",
    petToxicity: "non-toxic",
    careSummary:
      "Stunning patterned leaves that move with the day. Sensitive to tap water\u2014use filtered or rainwater.",
  },
  {
    commonName: "Philodendron",
    scientificName: "Philodendron hederaceum",
    careDifficulty: "easy",
    light: "Medium to bright indirect",
    water: "Water when top 2cm of soil is dry",
    humidity: "Average to high",
    temperature: "18-27\u00B0C (65-80\u00B0F)",
    soil: "Well-draining houseplant mix",
    fertilizer: "Balanced fertilizer monthly in growth",
    petToxicity: "toxic-pets",
    careSummary:
      "Fast trailer or climber depending on support. Easy to propagate and forgiving of light shifts.",
  },
  {
    commonName: "Anthurium",
    scientificName: "Anthurium andraeanum",
    careDifficulty: "moderate",
    light: "Bright indirect",
    water: "Water when top 2cm of soil is dry",
    humidity: "60% or higher",
    temperature: "18-27\u00B0C (65-80\u00B0F)",
    soil: "Chunky aroid mix",
    fertilizer: "Diluted phosphorus-rich feed for blooms",
    petToxicity: "toxic-pets",
    careSummary:
      "Long-lasting waxy blooms in red, pink, or white. Steady warmth and humidity keep it flowering.",
  },
  {
    commonName: "Orchid",
    scientificName: "Phalaenopsis spp.",
    careDifficulty: "moderate",
    light: "Bright indirect, no harsh sun",
    water: "Soak roots once a week, drain fully",
    humidity: "50-70%",
    temperature: "18-29\u00B0C (65-85\u00B0F)",
    soil: "Bark-based orchid mix",
    fertilizer: "Weak orchid fertilizer every other watering",
    petToxicity: "non-toxic",
    careSummary:
      "Reblooms reliably with bright light and a real dry-down between waterings. Avoid soggy bark.",
  },
  {
    commonName: "Boston Fern",
    scientificName: "Nephrolepis exaltata",
    careDifficulty: "moderate",
    light: "Bright indirect, gentle morning sun",
    water: "Keep consistently moist",
    humidity: "60% or higher",
    temperature: "16-24\u00B0C (60-75\u00B0F)",
    soil: "Peat-rich, moisture-retaining mix",
    fertilizer: "Half-strength balanced feed monthly",
    petToxicity: "non-toxic",
    careSummary:
      "Lush and pet-safe but loves humidity. A bathroom or kitchen with good light is ideal.",
  },
  {
    commonName: "String of Pearls",
    scientificName: "Curio rowleyanus",
    careDifficulty: "moderate",
    light: "Bright indirect with some sun",
    water: "Soak and dry, prone to rot",
    humidity: "Low",
    temperature: "18-24\u00B0C (65-75\u00B0F)",
    soil: "Cactus mix with extra perlite",
    fertilizer: "Light feed in spring and summer",
    petToxicity: "toxic-pets",
    careSummary:
      "Trailing succulent that hates wet roots. Shallow pots and a sunny shelf keep the strands plump.",
  },
  {
    commonName: "Chinese Money Plant",
    scientificName: "Pilea peperomioides",
    careDifficulty: "easy",
    light: "Bright indirect",
    water: "Water when top 2cm of soil is dry",
    humidity: "Average",
    temperature: "16-24\u00B0C (60-75\u00B0F)",
    soil: "Well-draining houseplant mix",
    fertilizer: "Balanced feed monthly in growth season",
    petToxicity: "non-toxic",
    careSummary:
      "Round coin-shaped leaves and quick pup production. Rotate often for an even shape.",
  },
  {
    commonName: "Dracaena",
    scientificName: "Dracaena marginata",
    careDifficulty: "easy",
    light: "Medium to bright indirect",
    water: "Let top half of soil dry between waterings",
    humidity: "Average",
    temperature: "18-27\u00B0C (65-80\u00B0F)",
    soil: "Well-draining houseplant mix",
    fertilizer: "Balanced feed every 2 months in growth",
    petToxicity: "toxic-pets",
    careSummary:
      "Slim sculptural tree. Sensitive to fluoride\u2014use filtered water if leaf tips brown.",
  },
  {
    commonName: "Dieffenbachia",
    scientificName: "Dieffenbachia seguine",
    careDifficulty: "moderate",
    light: "Medium to bright indirect",
    water: "Water when top 2-3cm of soil is dry",
    humidity: "50% or higher",
    temperature: "18-27\u00B0C (65-80\u00B0F)",
    soil: "Rich, well-draining mix",
    fertilizer: "Balanced fertilizer monthly in growth",
    petToxicity: "toxic-pets",
    careSummary:
      "Bold variegated foliage. Wear gloves when pruning\u2014the sap can irritate skin.",
  },
  {
    commonName: "Succulent Mix",
    scientificName: null,
    careDifficulty: "easy",
    light: "Bright direct or strong indirect",
    water: "Soak and fully dry between waterings",
    humidity: "Low",
    temperature: "13-27\u00B0C (55-80\u00B0F)",
    soil: "Gritty cactus and succulent mix",
    fertilizer: "Diluted cactus fertilizer in spring/summer",
    petToxicity: "unknown",
    careSummary:
      "Mixed planters of small succulents. Track each variety separately as you learn what each prefers.",
  },
];
